export enum ModalType {
  DEFAULT = 'DEFAULT',
  VIDEO = 'VIDEO',
  CHANNEL = 'CHANNEL',
  STUDENT_S_EVENT = 'STUDENT_S_EVENT',
  COURSE = 'COURSE',
  COMMUNITYFEED = 'COMMUNITYFEED',
  FEEDCOMMENT = 'FEEDCOMMENT',
  WORKSPACE = 'WORKSPACE',
  MILESTONES = 'MILESTONES',
  SHARE = 'SHARE',
  SUBSCRIPTION = 'SUBSCRIPTION',
  STUDENTS = 'STUDENTS'
}
